# Color profiles - general
CONF_PROFILE_GAMMA = "gamma"
CONF_PROFILE_WHITE_POINT_XY = "white_point_xy"

CONF_PROFILE_STANDARD_PROFILE = "standard"
CONF_PROFILE_STANDARD_PROFILE__LED = "led"
CONF_PROFILE_STANDARD_PROFILE__SRGB = "sRGB"
CONF_PROFILE_STANDARD_PROFILE__AdobeRGB_D55 = "AbobeRGB D55"
CONF_PROFILE_STANDARD_PROFILE__AdobeRGB_D65 = "AbobeRGB D65"
CONF_PROFILE_STANDARD_PROFILE__ACES_AP0 = "ACES AP0"

# Color profiles - RGB
CONF_PROFILE_RGB_COLOR_PROFILE_ID = "rgb_profile_id"
CONF_PROFILE_RGB_COLOR_PROFILE = "rgb_profile"

CONF_PROFILE_RED_XY = "red_xy"
CONF_PROFILE_GREEN_XY = "green_xy"
CONF_PROFILE_BLUE_XY = "blue_xy"

CONF_PROFILE_RED_WAVELENGTH = "red_wavelength"
CONF_PROFILE_GREEN_WAVELENGTH = "green_wavelength"
CONF_PROFILE_BLUE_WAVELENGTH = "blue_wavelength"

CONF_PROFILE_RED_INTENSITY = "red_intensity"
CONF_PROFILE_GREEN_INTENSITY = "green_intensity"
CONF_PROFILE_BLUE_INTENSITY = "blue_intensity"

# Color profiles - CWWW / W
CONF_PROFILE_CWWW_COLOR_PROFILE_ID = "cwww_profile_id"
CONF_PROFILE_CWWW_COLOR_PROFILE = "cwww_profile"

CONF_PROFILE_WHITE_COLOR_PROFILE_ID = "white_profile_id"
CONF_PROFILE_WHITE_COLOR_PROFILE = "white_profile"

CONF_PROFILE_WHITE_POINT_COLOR_TEMPERATURE = "white_point"
CONF_PROFILE_COLD_WHITE_COLOR_TEMPERATURE = "cold_white"
CONF_PROFILE_WARM_WHITE_COLOR_TEMPERATURE = "warm_white"

CONF_PROFILE_GREEN_TINT_IMPURITY = "green_tint_impurity"
CONF_PROFILE_PURPLE_TINT_IMPURITY = "purple_tint_impurity"

CONF_PROFILE_IMPURITY_GAMMA_DECAY = "impurity_gamma_decay"
CONF_PROFILE_RED_CCT_IMPURITY = "red_cct_impurity"
CONF_PROFILE_BLUE_CCT_IMPURITY = "blue_cct_impurity"